jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Build
        env:
          GMAIL_TOKEN: ${{ secrets.GMAIL_TOKEN }}
          GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
          GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}